---
- hosts: default
  roles:
    - hooks
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: stopped
      become: yes
      when: ansible_distribution == 'Amazon' and ansible_service_mgr == 'upstart' or ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'
